import { continueWithGoogle, ensureAnonymousSession, getSupabase } from "./discussion/supabase.js";
import { AuthState } from "./auth-state.js";
import { normalizeBookmarkId } from "./bookmark-identity.js";
import { diagnosticCount, diagnosticTiming } from "./diagnostics.js";

const el = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; };
const safeIdentity = user => user?.is_anonymous ? "Anonymous reader" : "Linked reader";
let disposeCurrent = null;
let renderGeneration = 0;
function tabUrl(tab){ return `/?account=${tab}`; }
function nav(active){ const n=el("nav","account-tabs"); [["profile","Profile"],["bookmarks","Bookmarks"],["settings","Settings"],["home","Home"]].forEach(([tab,label])=>{ const a=el("a",tab===active?"is-active":"",label); a.href=tab==="home"?"/":tabUrl(tab); n.append(a); }); return n; }
function shell(root,title,active){ const t=performance.now(); document.body.classList.remove("reader-active"); root.replaceChildren(); const wrap=el("main","account-root"); wrap.append(el("h1",null,title),nav(active)); root.append(wrap); diagnosticTiming("account.shell", performance.now()-t); return wrap; }
function setBusy(button, busy){ button.disabled = busy; button.dataset.loading = busy ? "true" : "false"; }
function authBox(wrap, refresh){ const box=el("section","account-card"); const status=el("p",null,"Checking account…"); const error=el("p","account-error"); const actions=el("div","account-actions"); box.append(el("h2",null,"Private account"),status,error,actions); wrap.append(box); const run=async(button, task)=>{ if(button.disabled) return; setBusy(button,true); error.textContent=""; try{ await task(); await AuthState.start({ retry: AuthState.snapshot().failed }); }catch(e){ error.textContent=e?.message || "That account action failed. Please retry."; }finally{ setBusy(button,false); } };
  const render=snap=>{ actions.replaceChildren(); if(!snap.ready){ status.textContent="Checking account…"; return; } if(snap.failed){ status.textContent="Account restoration is unavailable."; const retry=el("button",null,"Retry"); retry.onclick=()=>run(retry,()=>AuthState.retry()); actions.append(retry); return; } const { session }=snap; status.textContent=session?`Signed in as ${safeIdentity(session.user)}.`:"You are signed out."; if(!session){ const anon=el("button",null,"Continue anonymously"); anon.onclick=()=>run(anon,ensureAnonymousSession); actions.append(anon); } const google=el("button",null,session?.user?.is_anonymous?"Link Google account":"Continue with Google"); google.onclick=()=>run(google,continueWithGoogle); actions.append(google); if(session){ const out=el("button",null,"Sign out"); out.onclick=()=>run(out,async()=>{ const db=await getSupabase(); await db?.auth.signOut(); import("./preferences.js").then(({ TagPreferences }) => TagPreferences.clear()); }); actions.append(out); } };
  const unsub=AuthState.subscribe(snap=>{ render(snap); refresh?.(snap); }); return unsub; }
async function profile(root, alive){ const wrap=shell(root,"Account","profile"); alive.cleanups.push(authBox(wrap)); const info=el("section","account-card private"); const render=snap=>{ info.replaceChildren(el("h2",null,"Status")); if(!snap.ready) info.append(el("p",null,"Checking account…")); else if(!snap.session) info.append(el("p",null,"Sign in to view your private account.")); else info.append(el("p",null,`Account type: ${safeIdentity(snap.session.user)}.`), el("p",null,snap.session.user?.is_anonymous ? "This identity is anonymous." : "This identity is linked.")); }; alive.cleanups.push(AuthState.subscribe(render)); wrap.append(info); }
function cardFor(row, onEmpty, deps){ const { metadataForBookmarkId, setBookmark, tagsForWork } = deps; const id=normalizeBookmarkId(row.work_id); const work=metadataForBookmarkId(id); const card=el("article","bookmark-card"); card.dataset.bookmarkId=id; if(work?.thumb){ const img=new Image(); img.src=work.thumb; img.alt=""; img.loading="lazy"; card.append(img); } card.append(el("h3",null,work?.display || `Missing work ${id}`)); const tags=el("div","tag-list"); tagsForWork(work).forEach(t=>tags.append(el("span","tag-chip",t))); if(!tags.childElementCount) tags.append(el("span","tag-chip","No tags yet")); card.append(tags, el("p","bookmark-time", row.created_at ? `Saved ${new Date(row.created_at).toLocaleString()}` : "Saved")); if(work?.slug){ const a=el("a",null,"Read"); a.href=`/?source=${encodeURIComponent(work.source||"e")}&work=${encodeURIComponent(work.slug)}&chapter=${encodeURIComponent(work.chapters?.[0]||"chapter_1")}`; card.append(a); } const rm=el("button",null,"Remove"); rm.onclick=async()=>{ if(rm.disabled) return; rm.disabled=true; const parent=card.parentNode; const before=[...parent.children].indexOf(card); card.remove(); try{ await setBookmark(id,false); onEmpty?.(); }catch(e){ const ref=parent.children[before]||null; parent.insertBefore(card,ref); rm.disabled=false; parent.querySelector(".bookmark-empty")?.remove(); } }; card.append(rm); return card; }
async function bookmarks(root, alive){ const wrap=shell(root,"Bookmarks","bookmarks"); const { fetchBookmarkPage, metadataForBookmarkId, PAGE_SIZE, setBookmark, tagsForWork } = await import("./bookmark-service.js"); alive.cleanups.push(authBox(wrap, snap=>{ if(alive.lastUser!==undefined && alive.lastUser!==snap.userId) Account.render(); alive.lastUser=snap.userId; })); const list=el("section","account-card private"); list.append(el("h2",null,"Saved works")); wrap.append(list); const snap=AuthState.snapshot(); if(!snap.ready){list.append(el("p",null,"Checking account…")); return;} if(!snap.session){list.append(el("p",null,"Sign in to see bookmarks.")); return;} const grid=el("div","bookmark-grid"); list.append(grid); let from=0, seen=new Set(), loading=false, exhausted=false; const more=el("button",null,"Load More"); const empty=()=>{ if(!seen.size && exhausted && !grid.querySelector(".bookmark-empty")) grid.append(el("p","bookmark-empty","No bookmarks yet.")); };
 const load=async()=>{ if(loading||exhausted) return; loading=true; more.disabled=true; try{ const page=await fetchBookmarkPage({from,to:from+PAGE_SIZE-1}); if(!alive.current || AuthState.snapshot().userId!==snap.userId) return; for(const row of page.rows){ const id=normalizeBookmarkId(row.work_id); if(!id||seen.has(id)) continue; seen.add(id); grid.append(cardFor(row,()=>{seen.delete(id); if(!seen.size) empty();},{ metadataForBookmarkId, setBookmark, tagsForWork })); } from=page.nextFrom; exhausted=!page.hasMore; more.hidden=exhausted; empty(); }catch(e){ const retry=el("button",null,"Retry"); retry.onclick=load; grid.append(el("p",null,"Bookmarks are unavailable."),retry); } finally{ loading=false; more.disabled=false; }}; more.onclick=load; list.append(more); await load(); }
async function settings(root, alive){ const wrap=shell(root,"Settings","settings"); const [{ TagPreferences }, { knownTags, labelForTag, normalizeTag }] = await Promise.all([import("./preferences.js"), import("./tags.js")]); alive.cleanups.push(authBox(wrap, snap=>{ if(alive.lastUser!==undefined && alive.lastUser!==snap.userId) Account.render(); alive.lastUser=snap.userId; })); const panel=el("section","account-card private"); panel.append(el("h2",null,"Tag preferences")); wrap.append(panel); const auth=AuthState.snapshot(); if(!auth.ready){panel.append(el("p",null,"Checking account…")); return;} if(!auth.session){panel.append(el("p",null,"Sign in to save personal tag preferences.")); return;} const snap=await TagPreferences.loadForCurrentUser().catch(()=>TagPreferences.snapshot()); if(!alive.current || AuthState.snapshot().userId!==auth.userId) return; const tags=knownTags(); const q=el("input"); q.type="search"; q.placeholder="Search known tags"; const status=el("p","settings-status",tags.length?"Global defaults are local; personal exclusions are private.":"No authoritative tags are configured yet."); const list=el("div","tag-settings-list"); const selected=new Set(snap.personalExcluded); function draw(){ list.replaceChildren(); const query=normalizeTag(q.value); tags.filter(t=>!query||t.includes(query)).slice(0,100).forEach(t=>{ const label=el("label","tag-option"); const cb=document.createElement("input"); cb.type="checkbox"; cb.checked=selected.has(t); cb.onchange=()=>cb.checked?selected.add(t):selected.delete(t); label.append(cb,document.createTextNode(` ${labelForTag(t)}`)); list.append(label); }); } q.oninput=draw; const save=el("button",null,"Save preferences"); save.disabled=!tags.length; save.onclick=async()=>{ if(save.disabled) return; save.disabled=true; status.textContent="Saving…"; try{await TagPreferences.save({personalExcluded:[...selected],allowedDefaults:snap.allowedDefaults}); status.textContent="Saved.";}catch(e){status.textContent="Could not save. Retry when online.";}finally{save.disabled=false;}}; const restore=el("button",null,"Restore defaults"); restore.onclick=async()=>{selected.clear(); await TagPreferences.save({personalExcluded:[],allowedDefaults:snap.allowedDefaults}); draw(); status.textContent="Defaults restored.";}; panel.append(q,list,save,restore,status); draw(); }
export const Account={ render(){ disposeCurrent?.(); const generation=++renderGeneration; diagnosticCount("account.renderGeneration"); const alive={current:true,cleanups:[],lastUser:undefined}; disposeCurrent=()=>{alive.current=false; alive.cleanups.splice(0).forEach(fn=>fn?.());}; const root=document.getElementById("reader-container"); if(!root) return; const tab=new URLSearchParams(location.search).get("account")||"profile"; shell(root,tab==="bookmarks"?"Bookmarks":tab==="settings"?"Settings":"Account",tab); AuthState.start().then(()=>{ if(alive.current && generation===renderGeneration) Account.render(); }); const hydrate = tab==="bookmarks" ? bookmarks : tab==="settings" ? settings : profile; Promise.resolve(hydrate(root,alive)).catch(error=>{ if(!alive.current || generation!==renderGeneration) return; const wrap=shell(root,"Account unavailable",tab); const card=el("section","account-card private"); const retry=el("button",null,"Retry"); retry.onclick=()=>Account.render(); card.append(el("h2",null,"Account recovery"),el("p",null,error?.message || "This account view is unavailable."),retry); wrap.append(card); }); }, dispose(){ disposeCurrent?.(); disposeCurrent=null; }};
