import { continueWithGoogle, ensureAnonymousSession, getSupabase } from "./discussion/supabase.js";
import { AuthState } from "./auth-state.js";
import { navigate } from "./navigation.js";
import { TagPreferences } from "./preferences.js";
import { knownTags, labelForTag, normalizeTag } from "./tags.js";
import { fetchBookmarkPage, metadataForBookmarkId, normalizeBookmarkId, PAGE_SIZE, setBookmark, tagsForWork } from "./bookmark-service.js";

const el = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; };
const safeIdentity = user => user?.is_anonymous ? "Anonymous reader" : "Google-linked reader";
let disposeCurrent = null;
function tabUrl(tab){ return `/?account=${tab}`; }
function nav(active){ const n=el("nav","account-tabs"); [["profile","Profile"],["bookmarks","Bookmarks"],["settings","Settings"],["home","Home"]].forEach(([tab,label])=>{ const a=el("a",tab===active?"is-active":"",label); a.href=tab==="home"?"/":tabUrl(tab); n.append(a); }); return n; }
function shell(root,title,active){ document.body.classList.remove("reader-active"); root.replaceChildren(); const wrap=el("main","account-root"); wrap.append(el("h1",null,title),nav(active)); root.append(wrap); return wrap; }
function authBox(wrap){ const box=el("section","account-card"); const status=el("p",null,"Checking account…"); const actions=el("div","account-actions"); box.append(el("h2",null,"Private account"),status,actions); wrap.append(box); const render=({session})=>{ actions.replaceChildren(); status.textContent=session?`Signed in as ${safeIdentity(session.user)}.`:"You are signed out."; if(!session){ const anon=el("button",null,"Continue anonymously"); anon.onclick=async()=>{ await ensureAnonymousSession(); await AuthState.start(); }; actions.append(anon); } const google=el("button",null,session?.user?.is_anonymous?"Link Google account":"Continue with Google"); google.onclick=()=>continueWithGoogle(); actions.append(google); if(session){ const out=el("button",null,"Sign out"); out.onclick=async()=>{ const db=await getSupabase(); await db?.auth.signOut(); TagPreferences.clear(); document.querySelectorAll(".account-card.private").forEach(n=>n.replaceChildren(el("p",null,"Signed out."))); }; actions.append(out); } }; const unsub=AuthState.subscribe(render); return unsub; }
async function profile(root, alive){ const wrap=shell(root,"Account","profile"); const unsub=authBox(wrap); alive.cleanups.push(unsub); const info=el("section","account-card private"); info.append(el("h2",null,"Status"),el("p",null,"Bookmarks and settings are private to your current Supabase session. OAuth returns to /?account=profile&auth=callback on this origin."),el("p",null,"Use Bookmarks or Settings without a full page reload.")); wrap.append(info); }
function cardFor(row){ const id=normalizeBookmarkId(row.work_id); const work=metadataForBookmarkId(id); const card=el("article","bookmark-card"); card.dataset.bookmarkId=id; if(work?.thumb){ const img=new Image(); img.src=work.thumb; img.alt=""; img.loading="lazy"; card.append(img); } card.append(el("h3",null,work?.display || `Missing work ${id}`)); const tags=el("div","tag-list"); tagsForWork(work).forEach(t=>tags.append(el("span","tag-chip",t))); if(!tags.childElementCount) tags.append(el("span","tag-chip","No tags yet")); card.append(tags, el("p","bookmark-time", row.created_at ? `Saved ${new Date(row.created_at).toLocaleString()}` : "Saved")); if(work?.slug){ const a=el("a",null,"Read"); a.href=`/?source=${encodeURIComponent(work.source||"e")}&work=${encodeURIComponent(work.slug)}&chapter=${encodeURIComponent(work.chapters?.[0]||"chapter_1")}`; card.append(a); } const rm=el("button",null,"Remove"); rm.onclick=async()=>{ if(rm.disabled) return; rm.disabled=true; const parent=card.parentNode; const before=[...parent.children].indexOf(card); card.remove(); try{ await setBookmark(id,false); if(!parent.children.length) parent.append(el("p",null,"No bookmarks yet.")); }catch(e){ const ref=parent.children[before]||null; parent.insertBefore(card,ref); rm.disabled=false; alert("Could not remove bookmark. Please retry."); } }; card.append(rm); return card; }
async function bookmarks(root, alive){ const wrap=shell(root,"Bookmarks","bookmarks"); alive.cleanups.push(authBox(wrap)); const list=el("section","account-card private"); list.append(el("h2",null,"Saved works")); wrap.append(list); const snap=AuthState.snapshot(); if(!snap.session){list.append(el("p",null,"Sign in to see bookmarks.")); return;} const grid=el("div","bookmark-grid"); list.append(grid); let from=0, seen=new Set(), loading=false; const more=el("button",null,"Load More"); const load=async()=>{ if(loading) return; loading=true; more.disabled=true; try{ const page=await fetchBookmarkPage({from,to:from+PAGE_SIZE-1}); if(!alive.current) return; for(const row of page.rows){ const id=normalizeBookmarkId(row.work_id); if(!id||seen.has(id)) continue; seen.add(id); grid.append(cardFor(row)); } from=page.nextFrom; more.disabled=false; more.style.display=page.hasMore?"":"none"; if(!seen.size) grid.append(el("p",null,"No bookmarks yet.")); }catch(e){ grid.append(el("p",null,"Bookmarks are unavailable. Check connection and retry.")); more.disabled=false; } finally{ loading=false; }}; more.onclick=load; list.append(more); await load(); }
async function settings(root, alive){ const wrap=shell(root,"Settings","settings"); alive.cleanups.push(authBox(wrap)); const panel=el("section","account-card private"); panel.append(el("h2",null,"Tag preferences")); wrap.append(panel); if(!AuthState.snapshot().session){panel.append(el("p",null,"Sign in to save personal tag preferences.")); return;} const snap=await TagPreferences.loadForCurrentUser().catch(()=>TagPreferences.snapshot()); const tags=knownTags(); const q=el("input"); q.type="search"; q.placeholder="Search known tags"; const status=el("p","settings-status",tags.length?"Global defaults are local; personal exclusions are private.":"No authoritative tags are configured yet. Filtering controls are disabled until src/data/tags.json has memberships."); const list=el("div","tag-settings-list"); const selected=new Set(snap.personalExcluded); function draw(){ list.replaceChildren(); const query=normalizeTag(q.value); tags.filter(t=>!query||t.includes(query)).slice(0,100).forEach(t=>{ const label=el("label","tag-option"); const cb=document.createElement("input"); cb.type="checkbox"; cb.checked=selected.has(t); cb.onchange=()=>cb.checked?selected.add(t):selected.delete(t); label.append(cb,document.createTextNode(` ${labelForTag(t)}`)); list.append(label); }); } q.oninput=draw; const save=el("button",null,"Save preferences"); save.disabled=!tags.length; save.onclick=async()=>{ if(save.disabled) return; save.disabled=true; status.textContent="Saving…"; try{await TagPreferences.save({personalExcluded:[...selected],allowedDefaults:[]}); status.textContent="Saved.";}catch(e){status.textContent="Could not save. Retry when online.";}finally{save.disabled=false;}}; const restore=el("button",null,"Restore defaults"); restore.onclick=async()=>{selected.clear(); await TagPreferences.save({personalExcluded:[],allowedDefaults:[]}); draw(); status.textContent="Defaults restored.";}; panel.append(q,list,save,restore,status); draw(); }
export const Account={ async render(){ disposeCurrent?.(); const alive={current:true,cleanups:[]}; disposeCurrent=()=>{alive.current=false; alive.cleanups.splice(0).forEach(fn=>fn?.());}; const root=document.getElementById("reader-container"); if(!root) return; await AuthState.start(); const tab=new URLSearchParams(location.search).get("account")||"profile"; if(tab==="bookmarks") return bookmarks(root,alive); if(tab==="settings") return settings(root,alive); return profile(root,alive); }, dispose(){ disposeCurrent?.(); disposeCurrent=null; }};
